FROM ruby:3.3-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends bash && \
    rm -rf /var/lib/apt/lists/* && \
    gem install bashcov --no-document

WORKDIR /code

ENTRYPOINT ["bashcov"]
